name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install
        run: yarn
      - name: Run Linter
        run: yarn lint
      - name: Build Server
        run: yarn workspace server build
      - name: Build Website Bundle
        # temporarily disable CI flag to let warning not to fail the build
        run: CI=false yarn workspace client build
      - name: Unit Tests
        run: yarn workspace server test
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Cypress run
          uses: cypress-io/github-action@v1
          with:
            build: yarn workspaces run build
            start: yarn workpsace server start && yarn workspace client start
            wait-on: http://localhost:3000
          env: 
            ADMIN_DISABLED: "1"
