name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install
        run: yarn
      - name: Run Linter
        run: yarn lint
      - name: Build Server
        run: yarn workspace server build
      - name: Build Website Bundle
        # temporarily disable CI flag to let warning not to fail the build
        run: CI=false yarn workspace client build
      - name: Unit Tests
        run: yarn workspace server test
      - name: End to End Tests
        uses: cypress-io/github-action@v1
        with:
          start: yarn workspace server start && yarn workspace client start
          wait-on: http://localhost:3000
          wait-on-timeout: 180
        env: 
          ADMIN_DISABLED: "1"
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          MONGODB_URL: ${{ secrets.DEV_DB_URI }}
